name: Publish to crates.io
on:
  release:
    types:
      - published

jobs:
  publish:
    name: publish on crates.io
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo install toml-cli
      - run: test "v$(toml get -r Cargo.toml package.version)" = "${{ github.ref_name }}"
      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

